#!/bin/bash

MSG="update site"

while getopts "m:" opt; do
  case $opt in
    m) MSG="$OPTARG" ;;
    *) echo "Usage: ./publish [-m \"commit message\"]"; exit 1 ;;
  esac
done

quarto render
git add -A
git commit -m "$MSG"
git push
