### Selected Publications

1. **E. Morales-Cuadrado**, C. Llanes, Y. Wardi and S. Coogan, "Newton-Raphson Flow for Aggressive Quadrotor Tracking Control." [*2024 American Control Conference (ACC)*](https://arxiv.org/abs/2408.11197)
2. L. Baird, **E. Morales-Cuadrado**, and S. Coogan, "Runtime Assurance for Uncertain Systems from Interval Signal Temporal Logic." Submitted to IFAC Nonlinear Analysis: Hybrid Systems (NAHS). *(under revision)* %% [*arXiv preprint available.*](https://arxiv.org/abs/2408.11197)
3. **E. Morales-Cuadrado**, L. Baird, Y. Wardi and S. Coogan, "Lightweight Tracking Control for Computationally Constrained Aerial Systems with the Newton-Raphson Method." Submitted to IEEE Transactions on Control Systems Technology. *(under revision)* [*arXiv preprint available.*](hhttps://arxiv.org/abs/2508.14185)
4. **E. Morales-Cuadrado**, L. Chung, S. Kousik and S. Coogan, ": Fast, Safe Trajectory Planning for Systems under Unknown Disturbances." *Joint Submission to 2026 Modeling, Estimation and Control Conference (MECC) and ASME Letters in Dynamic Systems and Control (ALDSC)*. *(under revision)* %% [*arXiv preprint available.*](https://arxiv.org/abs/2408.11197)
5. **E. Morales-Cuadrado**, L. Chung, S. Kousik and S. Coogan, ": Fast, Safe Trajectory Planning for Systems under Unknown Disturbances." *Joint Submission to MECC-ALDSC*. *(under revision)* %% [*arXiv preprint available.*](https://arxiv.org/abs/2408.11197)
6. M. Cao, A. Harapanahalli, **E. Morales-Cuadrado**, and S. Coogan, "Trajectory Tracking for Systems with Unknown Time-Varying Disturbances." Submitted to Open Journal of Control Systems. *(under revision)* %% [*arXiv preprint available.*](https://arxiv.org/abs/2408.11197)
