### Selected Publications

1. **E. Morales-Cuadrado**, "[Lightweight Tracking Control for Computationally Constrained Aerial Systems with the Newton-Raphson Method.](https://mavmatrix.uta.edu/honors_spring2022/60/)" Undergraduate Honors College Thesis at UT Arlington, 2022.
2. **E. Morales-Cuadrado**, C. Llanes, Y. Wardi and S. Coogan, "Newton-Raphson Flow for Aggressive Quadrotor Tracking Control." [*2024 American Control Conference (ACC)*](https://arxiv.org/abs/2408.11197)
3. L. Baird, **E. Morales-Cuadrado**, and S. Coogan, "Runtime Assurance for Uncertain Systems from Interval Signal Temporal Logic." Submitted to IFAC Nonlinear Analysis: Hybrid Systems (NAHS), 2025. *(under revision)* [*preprint available.*](https://papers.ssrn.com/sol3/Delivery.cfm?abstractid=6168587)
4. **E. Morales-Cuadrado**, L. Baird, Y. Wardi and S. Coogan, "Lightweight Tracking Control for Computationally Constrained Aerial Systems with the Newton-Raphson Method." Submitted to IEEE Transactions on Control Systems Technology, 2026. *(under revision)* [*preprint available.*](https://arxiv.org/abs/2508.14185)
5. **E. Morales-Cuadrado**, L. Chung, S. Kousik and S. Coogan, "Fast, Safe Trajectory Planning for Systems under Unknown Disturbances." Joint Submission to 2026 MECC-ALDSC. *(under revision)*
